development:
  adapter: postgresql
  encoding: unicode
  database: YearbookApp_development
  pool: 5
  username: davekaplan
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: YearbookApp_test
  pool: 5
  username: davekaplan
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: YearbookApp_production
  pool: 5
  username: YearbookApp
  password:
